version: '3.3'
services:
    fivem:
        container_name: FiveM
        restart: on-failure
        environment:
            - LICENSE_KEY=<your-license-here>
        ports:
            - '30120:30120'
            - '30120:30120/udp'
        volumes:
            - './fivem:/config'
        image: spritsail/fivem
    
